version: '3.8'

services:
  camera:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /run/udev:/run/udev:ro
      - ./shared_volume:/tmp/annotated_output  # Mount host directory to container's output directory
    ports:
      - "8000:8000"
    restart: always
    privileged: true

